server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Ancien site PHP → nouvelles pages
    location ^~ /news/ {
        return 301 https://cltobadminton.fr/actualites;
    }
    
    location ^~ /news/news_controller/detailNews/1119 {
        return 301 https://cltobadminton.fr/actualite/g5objva6agvnzm6tp90ex358;
    }

    location ^~ /club/ {
        return 301 https://cltobadminton.fr;
    }

    location ^~ /jeunes/(jeunes_controller/espaceJeunes)?/?$ {
        return 301 https://cltobadminton.fr/jeunes;
    }

    # Redirect all /competitions/* and the specific espaceCompetiteur to the same destination
    location ~* ^/competitions(/competitions_controller/espaceCompetiteur)?/?$ {
        return 301 https://cltobadminton.fr/adultes-competiteurs;
    }

    location ^~ /jouer/jouer_controller/gymnase {
        return 301 https://cltobadminton.fr/gymnases;
    }

    location ^~ /jouer/jouer_controller/crenaux {
        return 301 https://cltobadminton.fr/crenaux;
    }

    location ^~ /jouer/ {
        return 301 https://cltobadminton.fr/crenaux;
    }

    location ^~ /contact {
        return 301 https://cltobadminton.fr/contact;
    }

    # Autres préfixes anciens fréquents (à adapter selon GSC)
    # location ^~ /news_controller/ { return 301 https://cltobadminton.fr/actualites; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}